#Goal: to learn CI_CD piepline(Test dummy)
name: CI_CD piepline demo

on: 
 push: 
  branches: [main]

jobs: 
  code: 
   runs-on: ubuntu-latest
   steps: 
   - name: clone the latest code 
     run: echo"Code Clonned"
  build: 
    needs: code
    runs-on: ubuntu-latest
    steps: 
    - name: Build the clonned code using Docker
      run: echo"Code Builded"
  test:
    needs: build
    runs-on: ubantu-latest
    steps: 
    - name: Test the latest code build 
      run: echo"Code Test Successful"
  
  deploy: 
    needs: [code,build,test]
    runs-on: ubantu-latest
    steps: 
    - name: Deploy the Test code
      run: echo"Deployment completed"
